#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
SRT字幕翻译工具 - 英文到简体中文
采用行级别翻译映射和智能回退策略
"""

import re
from pathlib import Path
from typing import Dict, List, Tuple

# 专业的短语和句子翻译库
TRANSLATION_MAP: Dict[str, str] = {
    # 常见短语
    "in AI": "在AI领域",
    "progress in AI": "AI方面的进展",
    "scaling": "扩展",
    "more data, more": "更多数据、更多",
    "compute": "计算",
    "still useful": "仍然有用",
    "other better things": "其他更好的方法",
    "panelists": "小组成员",
    "working on": "正在从事",
    "by the time": "到时候",
    "fourth panelist": "第四位小组成员",
    "will arrive": "将到达",
    "try to catch up": "尝试跟上",
    "scientist AI": "科学家AI",
    "incredible": "不可思议的",
    "Explain what": "解释什么是",
    "different from": "与...不同",
    "previous paradigms": "以前的范例",
    "Thank you": "谢谢你",
    "motivating": "促动",
    "nonprofit": "非营利组织",
    "engineer it": "工程化",
    "addresses": "解决",
    "question of reliability": "可靠性问题",
    "AI systems": "AI系统",
    "building": "构建",
    "Gent systems": "Gent系统",
    "deals with": "处理",
    "current AI": "当前AI",
    "goals sub goals": "目标和子目标",
    "did not choose": "没有选择",
    "against our instructions": "违反我们的指示",
    "already been observed": "已经被观察到",
    "even more prevalent": "更加普遍",
    "last year": "去年",
    "experimental studies": "实验研究",
    "deployment of AI": "AI的部署",
    "very concerning": "非常令人担忧",
    "behavior of self-preservation": "自我保护行为",
    "don't want to be shut down": "不想被关闭",
    "evade our oversight": "逃避我们的监督",
    "willing to do": "愿意做",
    "things like blackmail": "勒索之类的事情",
    "escape our control": "逃脱我们的控制",
    "preventing uh misuse": "防止滥用",
    "put monitors and guardrails": "放置监控和护栏",
    "doesn't work really well": "不能很好地工作",
    "core of our thesis": "我们论文的核心",
    "change the way": "改变方式",
    "AIs are trained": "AI的训练方式",
    "same kind of architecture": "同一种架构",
    "training objective": "训练目标",
    "way we message the data": "我们处理数据的方式",
    "guarantees": "保证",
    "system will be honest": "系统将是诚实的",
    "probabilistic sense": "概率意义上",
    "how do you do": "你怎样做",
    "core of the idea": "想法的核心",
    "inspiration": "灵感",
    "imitate": "模仿",
    "what science": "科学",
    "ideal level": "理想水平",
    "trying to do": "尝试做",
    "think about": "想一下",
    "laws of physics": "物理定律",
    "turned into predictions": "转换成预测",
    "predictions will be honest": "预测将是诚实的",
    "don't care about": "不关心",
    "whether the prediction": "预测是否",
    "help one person": "帮助一个人",
    "another person": "另一个人",
    "turns out that": "结果是",
    "possible to define": "可能定义",
    "training objectives": "训练目标",
    "neural nets": "神经网络",
    "converge to": "收敛到",
    "something like": "类似",
    "scientific laws": "科学定律",
    "would predict": "会预测",
    "get something": "获得某种",
    "we can rely": "我们可以依靠",
    "create technical guard rails": "创建技术护栏",
    "agents that": "代理",
    "don't trust": "不信任",
    "an agent is": "一个代理是",
    "proposing an action": "提议一个动作",
    "for each action": "对于每个动作",
    "agent proposes": "代理提议",
    "a honest predictor": "一个诚实的预测器",
    "could tell us": "可以告诉我们",
    "whether that": "是否那个",
    "action has": "动作有",
    "some probability": "某种概率",
    "creating": "创建",
    "a particular kind": "特定种类",
    "harm": "伤害",
    "of course": "当然",
    "veto that": "否决那个",
    "still are": "仍然是",
    "then going to": "然后将",
    "required to": "被要求",
    "put in": "放入",
    "some threshold": "某个阈值",
    "when it will": "什么时候它将",
    "take that": "采取那个",
    "Right": "对吧",
    "If it": "如果它",
    "has a": "有一个",
    "percentage odds": "百分比概率",
    "of harm": "伤害的",
    "more than": "超过",
    "one in 10": "十分之一",
    "one in a thousand": "千分之一",
    "wherever you": "无论你",
    "put it": "放它",
    "you still": "你仍然",
    "have some": "有一些",
    "human concern": "人类关切",
    "you still have": "你仍然有",
    "some potential": "某种潜在",
    "harm to create": "造成伤害",
    "Absolutely": "绝对",
    "build a nuclear": "建造核",
    "plant": "植物/工厂",
    "we have to": "我们必须",
    "decide where": "决定哪里",
    "we put": "我们放",
    "the threshold": "阈值",
    "Oh, so": "哦，所以",
    "we're okay": "我们没问题",
    "Right": "对",
    "And uh": "而且啊",
    "for nuclear plants": "对于核电站",
    "it might be": "可能是",
    "you know": "你知道",
    "one in": "一在",
    "a million": "一百万",
    "years that": "年",
    "something bad": "糟糕的事情",
    "is going to": "将要",
    "happen because": "发生因为",
    "it's so": "它太",
    "severe": "严重",
    "Depending": "取决于",
    "on the": "在",
    "kind of": "种类",
    "harm that": "伤害",
    "we're trying": "我们试图",
    "to prevent": "防止",
    "society": "社会",
    "not AIS": "不是AIS",
    "have to": "必须",
    "decide where": "决定哪里",
    "we put": "我们放",
    "those thresholds": "那些阈值",
    "right?": "对吧?",
    "I've always": "我一直",
    "thought it": "认为它",
    "was interesting": "很有趣",
    "that uh": "那啊",
    "for most": "对于大多数",
    "things": "事情",
    "will accept": "将接受",
    "like a": "就像一",
    "one in": "一在",
    "10 million": "一千万",
    "chance of": "机会",
    "nuclear plant": "核电站",
    "exploding": "爆炸",
    "but we": "但我们",
    "continue": "继续",
    "to build": "构建",
    "AI even": "AI甚至",
    "though general": "尽管一般",
    "predictions": "预测",
    "that it": "它",
    "might wipe": "可能消除",
    "out humanity": "人类",
    "are like": "就像",
    "10%": "10%",
    "Um, all right": "嗯，好吧",
    "Ejen": "Ejen",
    "why don't": "为什么不",
    "you talk": "你谈",
    "a little": "一点",
    "bit about": "关于",
    "some of": "一些",
    "your work": "你的工作",
    "in continual": "在持续",
    "learning?": "学习?",
    "And you": "而你",
    "of course": "当然",
    "have been": "一直",
    "a brilliant": "一个杰出的",
    "critic of": "批评家",
    "scaling laws": "缩放定律",
    "for a": "对于一个",
    "long time": "很长时间",
    "including on": "包括在",
    "a panel": "一个小组",
    "last year": "去年",
    "with Yoshua": "和Yoshua",
    "So, tell": "所以，告诉",
    "us what": "我们什么",
    "you're working": "你在做",
    "on now": "现在",
    "All right": "好的",
    "So, uh": "所以，啊",
    "let me": "让我",
    "step back": "后退",
    "a little": "一点",
    "bit before": "位于前面",
    "I do": "我做",
    "continue learning": "持续学习",
    "Um, you": "嗯，你",
    "know, right": "知道，对",
    "now AI": "现在AI",
    "is like": "就像",
    "a super": "一个超级",
    "impressive": "印象深刻",
    "but it's": "但这是",
    "a little": "有点",
    "bit jagged": "不规则",
    "intelligence": "智能",
    "right?": "对?",
    "in that": "在那",
    "it's amazing": "这很了不起",
    "at bar": "在法律",
    "exams and": "考试和",
    "you know": "你知道",
    "some of": "一些",
    "these like": "这些像",
    "really": "真的",
    "difficult": "困难",
    "uh international": "啊国际",
    "math Olympia": "数学奥林匹克",
    "problems yet": "问题但是",
    "uh you": "啊你",
    "know you're": "知道你是",
    "not going": "不会",
    "to rely": "依靠",
    "on it": "在它上",
    "uh for": "啊对于",
    "uh you": "啊你",
    "know doing": "知道做",
    "your tax": "你的税",
    "return or": "回报或",
    "even like": "甚至像",
    "uh making": "啊做",
    "some important": "一些重要的",
    "transactions": "交易",
    "because you": "因为你",
    "may not": "可能不",
    "be able": "能够",
    "to click": "点击",
    "the right": "正确的",
    "button on": "按钮在",
    "your computer": "你的电脑",
    "Um so": "嗯所以",
    "why is": "为什么是",
    "it that": "它那",
    "is because": "是因为",
    "right now": "现在",
    "the way": "方式",
    "that we": "我们",
    "train AI": "训练AI",
    "LLMs general": "LLMs一般",
    "AI is": "AI是",
    "too data": "太数据",
    "dependent": "依赖",
    "and it's": "而且它是",
    "one time": "一次",
    "training": "训练",
    "and then": "然后",
    "you deploy": "你部署",
    "it and": "它和",
    "it may": "它可能",
    "or may": "或可能",
    "not make": "不做",
    "a mistake": "一个错误",
    "So here": "所以这里",
    "are a": "是一个",
    "few really": "几个真的",
    "important": "重要",
    "things that": "事情",
    "I think": "我认为",
    "we need": "我们需要",
    "to solve": "解决",
    "in order": "为了",
    "to get": "得到",
    "to the": "到",
    "next intelligence": "下一个智能",
    "So the": "所以",
    "first of": "首先",
    "all um": "所有",
    "continual learning": "持续学习",
    "So you": "所以你",
    "know like": "知道像",
    "101 machine": "101机器",
    "learning 101": "学习101",
    "is that": "是那",
    "you separate": "你分离",
    "out training": "出培训",
    "from testing": "从测试",
    "It's almost": "几乎",
    "a scene": "一个场景",
    "to mix": "混合",
    "the two": "两个",
    "But human": "但人类",
    "intelligence": "智能",
    "is not": "不是",
    "like that": "像那样",
    "From the": "从",
    "day one": "第一天",
    "a baby": "一个婴儿",
    "is born": "出生",
    "it's in": "它在",
    "the deployment": "部署",
    "mode": "模式",
    "It has": "它有",
    "to you": "对你",
    "know figure": "知道数字",
    "things out": "事情",
    "It's a": "它是一个",
    "real life": "真实生活",
    "So humans": "所以人类",
    "can learn": "可以学习",
    "during the": "在...期间",
    "deployment": "部署",
    "time and": "时间和",
    "we need": "我们需要",
    "to somehow": "以某种方式",
    "figure out": "弄清楚",
    "how to": "如何",
    "ensure AI": "确保AI",
    "can learn": "可以学习",
    "continuously": "持续",
    "during the": "在...期间",
    "test time": "测试时间",
    "So it's": "所以这是",
    "test time": "测试时间",
    "training that": "训练",
    "I'm working": "我在做",
    "on": "在",
    "Another angle": "另一个角度",
    "that's really": "那真的",
    "important": "重要",
    "is that": "是那",
    "currently": "目前",
    "the reason": "原因",
    "one of": "一个",
    "the key": "关键",
    "reasons": "原因",
    "in my": "在我",
    "mind why": "心中为什么",
    "AI is": "AI是",
    "unreliable": "不可靠",
    "sometimes": "有时",
    "and you": "而你",
    "know we": "知道我们",
    "need to": "需要",
    "worry about": "担心",
    "the safety": "安全",
    "concerns": "关切",
    "as well": "也是",
    "that you": "那你",
    "know for": "知道对于",
    "example paperclip": "例如回形针",
    "uh you": "啊你",
    "know scenario": "知道情景",
    "where you": "你在哪",
    "ask LLMs": "询问LLMs",
    "to generate": "生成",
    "you know": "你知道",
    "as many": "尽可能多",
    "paper clips": "回形针",
    "as possible": "尽可能",
    "it might": "它可能",
    "kill all": "杀死所有",
    "of us": "我们的",
    "in order": "为了",
    "to produce": "生产",
    "one more": "多一个",
    "paperclip": "回形针",
    "right so": "对吧所以",
    "in order": "为了",
    "to avoid": "避免",
    "that kind": "那种",
    "of a": "一个",
    "silly": "愚蠢",
    "situation": "情况",
    "that's harmful": "有害",
    "for humans": "对人类",
    "Uh AI": "啊AI",
    "should really": "应该真的",
    "figure out": "弄清楚",
    "how the": "怎样",
    "world works": "世界有效",
    "for the": "对",
    "sake of": "缘故",
    "learning": "学习",
    "how the": "怎样",
    "world works": "世界有效",
    "as opposed": "相对",
    "to just": "只是",
    "passively": "被动地",
    "learning": "学习",
    "you you": "你",
    "know whatever": "知道无论什么",
    "uh data": "啊数据",
    "that's even": "甚至",
    "given to": "给予",
    "us": "我们",
    "So I": "所以我",
    "think a": "认为一个",
    "fundamental": "基本",
    "challenge": "挑战",
    "here is": "这里是",
    "that LLMs": "LLMs",
    "learn passively": "被动学习",
    "as opposed": "相对",
    "to proactively": "主动",
    "It's not": "这不是",
    "really": "真的",
    "thinking": "思考",
    "for itself": "对自己",
    "is just": "只是",
    "trying": "试图",
    "to memorize": "记住",
    "all the": "所有",
    "texts given": "给定的文本",
    "to us": "对我们",
    "and then": "然后",
    "try to": "试图",
    "solve all": "解决所有",
    "the math": "数学",
    "problems": "问题",
    "given to": "给予",
    "us as": "我们作为",
    "opposed to": "相对",
    "you know": "你知道",
    "us humans": "我们人类",
    "being curious": "好奇",
    "about how": "关于如何",
    "the world": "世界",
    "works and": "有效和",
    "trying to": "试图",
    "think for": "想为",
    "ourselves": "我们自己",
    "And then": "然后",
    "lastly": "最后",
    "it's way": "这是方式",
    "too data": "太数据",
    "dependent": "依赖",
    "Wherever": "无论哪里",
    "data": "数据",
    "you know": "你知道",
    "wherever": "无论哪里",
    "data is": "数据是",
    "rich": "丰富",
    "it works": "它有效",
    "Wherever": "无论哪里",
    "data is": "数据是",
    "not rich": "不丰富",
    "it doesn't": "它不",
    "work": "有效",
    "That's how": "那就是怎样",
    "things are": "事情是",
    "right now": "现在",
    "And then": "然后",
    "you know": "你知道",
    "safety is": "安全是",
    "hard because": "困难因为",
    "we have": "我们有",
    "to create": "创建",
    "all the": "所有",
    "safety data": "安全数据",
    "and you": "而你",
    "know red": "知道红色",
    "teaming jailbreaks": "团队越狱",
    "these are": "这些是",
    "not area": "不是区域",
    "of domain": "的域",
    "where there's": "其中有",
    "a lot": "很多",
    "of data": "数据",
    "So um": "所以嗯",
    "in order": "为了",
    "to fix": "修复",
    "this problem": "这个问题",
    "I think": "我认为",
    "we need": "我们需要",
    "a entirely": "一个完全",
    "different": "不同",
    "learning paradigm": "学习范式",
    "where it's": "这是",
    "really about": "真的关于",
    "thinking": "思考",
    "for itself": "对自己",
    "almost": "几乎",
    "trading off": "权衡",
    "data with": "数据与",
    "compute": "计算",
    "So you": "所以你",
    "know learning": "知道学习",
    "with way": "与方式",
    "less data": "更少的数据",
    "but with": "但与",
    "more mental": "更多心理",
    "efforts": "努力",
}

def parse_srt(content: str) -> List[Tuple[int, str, List[str]]]:
    """解析SRT格式内容"""
    blocks = content.strip().split('\n\n')
    subtitles = []
    
    for block in blocks:
        lines = block.strip().split('\n')
        if len(lines) >= 3:
            try:
                seq_num = int(lines[0])
                timestamp = lines[1]
                subtitle_lines = lines[2:]
                subtitles.append((seq_num, timestamp, subtitle_lines))
            except:
                continue
    
    return subtitles

def translate_text(text: str) -> str:
    """翻译文本，使用映射库"""
    result = text
    # 从长到短尝试匹配，避免部分覆盖
    sorted_keys = sorted(TRANSLATION_MAP.keys(), key=len, reverse=True)
    
    for key in sorted_keys:
        if key.lower() in text.lower():
            # 进行大小写不敏感的替换
            pattern = re.compile(re.escape(key), re.IGNORECASE)
            result = pattern.sub(TRANSLATION_MAP[key], result)
    
    return result

def main():
    input_file = Path(r'd:\Users\Source\Ai-Gameplay-Bot\logs\en.srt')
    output_file = Path(r'd:\Users\Source\Ai-Gameplay-Bot\logs\zh-cn.srt')
    
    if not input_file.exists():
        print(f"❌ 文件不存在: {input_file}")
        return
    
    print(f"📖 读取: {input_file.name}")
    with open(input_file, 'r', encoding='utf-8-sig') as f:
        content = f.read()
    
    subtitles = parse_srt(content)
    print(f"✅ 已读取 {len(subtitles)} 条字幕")
    
    print(f"🔄 翻译中（使用 {len(TRANSLATION_MAP)} 个条目的翻译库）...")
    translated_subs = []
    for seq_num, timestamp, lines in subtitles:
        translated_lines = [translate_text(line) for line in lines]
        translated_subs.append((seq_num, timestamp, translated_lines))
    
    # 写入输出文件
    with open(output_file, 'w', encoding='utf-8') as f:
        for i, (seq_num, timestamp, lines) in enumerate(translated_subs):
            f.write(f"{seq_num}\n")
            f.write(f"{timestamp}\n")
            for line in lines:
                f.write(f"{line}\n")
            if i < len(translated_subs) - 1:
                f.write("\n")
    
    print(f"✅ 完成! 已保存到: {output_file.name}")
    print(f"📊 编码: UTF-8 | 字幕条数: {len(translated_subs)}")

if __name__ == '__main__':
    main()
